version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  sungwon-movie-deployment:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - checkout
      - run:
          name: check
          command: bash ./.circleci/check.sh JeongSungwon/movie
      - run:
          name: Install and configure dependencies
          command: |
            cd JeongSungwon/movie
            git config user.email "chsw93@gmail.com"
            git config user.name "sungwon"
            npm install
      - add_ssh_keys:
          fingerprints:
            - "c7:70:51:47:98:4e:a1:da:30:e6:a3:7a:63:d1:9a:13"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd JeongSungwon/movie
            npm run deploy
  jehwan-movie-deployment:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - checkout
      - run:
          name: check
          command: bash ./.circleci/check.sh LeeJehwan/movie
      - run:
          name: Install and configure dependencies
          command: |
            cd LeeJehwan/movie
            git config user.email "wpghks7@naver.com"
            git config user.name "leejehwan"
            npm install
      - add_ssh_keys:
          fingerprints:
            - "c7:70:51:47:98:4e:a1:da:30:e6:a3:7a:63:d1:9a:13"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd LeeJehwan/movie
            npm run deploy
  daehyun-movie-deployment:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - checkout
      - run:
          name: check
          command: bash ./.circleci/check.sh AhnDaeHyun/movie
      - run:
          name: Install and configure dependencies
          command: |
            cd AhnDaeHyun/movie
            git config user.email "daehyun1023@naver.com"
            git config user.name "daehyun1023"
            npm install
      - add_ssh_keys:
          fingerprints:
            - "c7:70:51:47:98:4e:a1:da:30:e6:a3:7a:63:d1:9a:13"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd AhnDaeHyun/movie
            npm run deploy
  hamjins-movie-deployment:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - checkout
      - run:
          name: check
          command: bash ./.circleci/check.sh hamjins/movie
      - run:
          name: Install and configure dependencies
          command: |
            cd hamjins/movie
            git config user.email "coronal95@naver.com"
            git config user.name "hamjins"
            npm install
            npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "c7:70:51:47:98:4e:a1:da:30:e6:a3:7a:63:d1:9a:13"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd hamjins/movie
            npm run deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - sungwon-movie-deployment:
          filters:
            branches:
              only:
                - main
      - jehwan-movie-deployment:
          filters:
            branches:
              only:
                - main
      - daehyun-movie-deployment:
          filters:
            branches:
              only:
                - main
      - hamjins-movie-deployment:
          filters:
            branches:
              only:
                - main
